### ISSUE TITLE
KOS exclusive terminal input

### ISSUE THREAD

**Issue by JSRRosenbaum** [linuxgurugamer/KSP-ProbeControlRoom#1]
KSP: 1.8.1 Windows 64bit
Problem: KOS input exclusivity ignored

Mods installed:

	Module Manager 4.1.3
	ClickThroughBlocker 0.1.9.5
	ToolbarControl 0.1.9.4
	RasterPropMonitor (adopted) 0.31
	
	KOS 1.2.1.0
	Probe Control Room Recontrolled 1.2.3
	
Reproduction steps:

Go to Launchpad with a vehicle that has a KOS module installed. 
Right Click KOS module and select open terminal
Click the terminal window to send input there
Press the 'c' key

(regular IVA switching does not ignore the input exclusivity, but PCR's does)

Log:

https://drive.google.com/open?id=19DivKYAOjlS9NHGSKaZSYRH_uZe3JQoq (Player.log)

**Comment by linuxgurugamer** [comment]
Nothing I can do about that.  That's a bug with KoS, allowing click-through to fall through to other windows.  Ask the KoS people to start using the ClickThroughBlocker to fix

**Comment by JSRRosenbaum** [comment]
KSP: 1.8.1 Windows 64bit
Problem: KOS input exclusivity ignored

Mods installed:

	Module Manager 4.1.3
	ClickThroughBlocker 0.1.9.5
	ToolbarControl 0.1.9.4
	RasterPropMonitor (adopted) 0.31
	
	KOS 1.2.1.0
	Probe Control Room Recontrolled 1.2.3
	
Reproduction steps:

Go to Launchpad with a vehicle that has a KOS module installed. 
Right Click KOS module and select open terminal
Click the terminal window to send input there
Press the 'c' key

(regular IVA switching does not ignore the input exclusivity, but PCR's does)

Log:

https://drive.google.com/open?id=19DivKYAOjlS9NHGSKaZSYRH_uZe3JQoq (Player.log)
